name: login_screen
version: 0.7.0
description: >-
  Login Screen Template.
  Provide template with customizable parameters.
repository: https://github.com/LCostaN/LoginScreen
homepage: https://github.com/LCostaN/LoginScreen

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
